repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'cd test && pytest'
        language: system
        pass_filenames: false
        always_run: true