---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template to alarm an application-sam model"
Resources: {% for item in DLQ %}
  DLQAlarm{{ DLQ[loop.index0].id }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "{{ DLQ[loop.index0].QueueName }}-VisibleMessagesAlert"
      AlarmActions:
        - {{ DLQ[loop.index0].ResponseARN }}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: {{ DLQ[loop.index0].QueueName }}
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 60
      Statistic: Average
      Threshold: '1'

  {% endfor %}