---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template to alarm an application-sam model"
Resources: {% for item in EC2 %}
  EC2CPUAlarm{{ EC2[loop.index0].id }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "{{ EC2[loop.index0].InstanceId }}-EC2-High-CPU"
      AlarmActions:
        - {{ EC2[loop.index0].ResponseARN }}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: {{ EC2[loop.index0].InstanceId }}
      EvaluationPeriods: 3
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Statistic: Average
      Threshold: {{ EC2[loop.index0].CPUThreshold }}

  EC2StatusAlarm{{ EC2[loop.index0].id }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "{{EC2[loop.index0].InstanceId }}-EC2-StatusCheck-Error"
      AlarmActions:
        - {{ EC2[loop.index0].ResponseARN }}
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: {{ EC2[loop.index0].InstanceId}}
      EvaluationPeriods: 15
      MetricName: StatusCheckFailed_System
      Namespace: AWS/EC2
      Period: 60
      Statistic: SampleCount
      Threshold: {{ EC2[loop.index0].StatusThreshold }}
  {% endfor %}
  {% for item in EC2Alerts.RAM %}
  EC2RAMAlarm{{ EC2Alerts.RAM[loop.index0].id }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "{{ EC2Alerts.RAM[loop.index0].InstanceId }}-EC2-High-RAM-Usage"
      AlarmActions:
        - {{ EC2Alerts.RAM[loop.index0].ResponseARN }}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: {{ EC2Alerts.RAM[loop.index0].InstanceId }}
      EvaluationPeriods: 3
      MetricName: mem_used_percent
      Namespace: custom/EC2
      Period: 60
      Statistic: Average
      Threshold: {{ EC2Alerts.RAM[loop.index0].Threshold }}
  {% endfor %}
  {% for item in EC2Alerts.Disk %}
  EC2DiskAlarm{{ EC2Alerts.Disk[loop.index0].id }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "{{ EC2Alerts.Disk[loop.index0].InstanceId }}-EC2-High-Disk-Usage"
      AlarmActions:
        - {{ EC2Alerts.Disk[loop.index0].ResponseARN }}
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: {{ EC2Alerts.Disk[loop.index0].InstanceId }}
      EvaluationPeriods: 3
      MetricName: disk_used_percent
      Namespace: custom/EC2
      Period: 60
      Statistic: Average
      Threshold: {{ EC2Alerts.Disk[loop.index0].Threshold }}
  {% endfor %}